# Generated by Django 3.2.5 on 2022-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target1_etc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
